name: Deploy GWT to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17  # Было 11, ставим 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Здесь тоже меняем на 17
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests -f mail/pom.xml

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # Если сборка пройдет, но деплой упадет — проверим этот путь
        folder: mail/mail-client/target/mail-client-2.13.0-SNAPSHOT
        branch: gh-pages
        
