name: Deploy GWT to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests -f mail/pom.xml

    - name: Find Deploy Folder
      # Этот скрипт ищет папку, которая начинается на mail-client- в target
      id: find_folder
      run: |
        FOLDER_PATH=$(find mail/mail-client/target -maxdepth 1 -type d -name "mail-client-*" | head -n 1)
        echo "DEPLOY_FOLDER=$FOLDER_PATH" >> $GITHUB_OUTPUT

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # Используем найденный путь из предыдущего шага
        folder: ${{ steps.find_folder.outputs.DEPLOY_FOLDER }}
        branch: gh-pages
        
